### ISSUE TITLE
Sustainability plan (D5.4)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/horizon-zen#30]

**Comment by nemobis** [comment]
To reduce transaction costs, the European Commission should grant Zenodo a sub-licensable copyright license to all materials and publications arising from all past and future Horizon grants. Everyone applying for such grants has signed a grant agreement which gives the EU a very broad inbound license.

This will simplify mediated deposit (e.g. by university librarians/repository managers), metadata curation before deposit, moderation after deposit, as well as dissemination outside Zenodo (if Zenodo then applies a free or semi-free Creative Commons license as outbound license).
